---
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
      -
        subnet: 10.10.0.0/24
      driver: default
services:
  memcached:
    image: "memcached:1.5.7"
    container_name: memcached1.5.7
    expose:
    - "11211"
    ports:
    - "11211:11211"
    networks:
    - vpcbr

  mysql:
    #build: ./mysql
    image: mysql:5.7
    container_name: mysql5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    expose:
    - "3306"
    ports:
    - "3306:3306"
    restart: always
    volumes:
    - "../data/db/mysql:/var/lib/mysql:rw"
    - "../data/logs/mysql:/var/lib/mysql-logs:rw"
    - "./mysql/conf.d:/etc/mysql/conf.d:ro"
    networks:
      vpcbr:
        ipv4_address: "10.10.0.100"
  redis:
    image: redis:4.0
    container_name: redis4.0
    expose:
    - "6379"
    ports:
    - "6379:6379"
    networks:
    - vpcbr
    restart: always
    volumes:
    - "./redis/redis.conf:/usr/local/redis/etc/redis.conf"
    - "../data/db/redis:/usr/local/redis/data"
    - "../data/logs/redis:/usr/local/redis/logs"
    command: redis-server /usr/local/redis/etc/redis.conf

  php56:
    build: ./php56/
    command: php-fpm
    depends_on:
    - mysql
    - redis
    - memcached
    links:
    - mysql
    - redis
    - memcached
    networks:
    - vpcbr
    restart: always
    volumes:
    - "../data/www:/data/www:rw"
    - "../data/logs/php56-fpm:/var/log/php-fpm:rw"
    - "./php56/php.ini:/usr/local/etc/php/php.ini:ro"
    - "./php56/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro"
  php72:
    build: ./php72/
    command: php-fpm
    depends_on:
    - mysql
    - redis
    - memcached
    links:
    - mysql
    - redis
    - memcached
    networks:
    - vpcbr
    restart: always
    volumes:
    - "../data/www:/data/www:rw"
    - "../data/logs/php72-fpm:/var/log/php-fpm:rw"
    - "./php72/php.ini:/usr/local/etc/php/php.ini:ro"
    - "./php72/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro"

  nginx:
    image: nginx:1.12
    container_name: nginx1.12
    depends_on:
    - php56
    - php72
    links:
    - "php72:php72-fpm"
    - "php56:php56-fpm"
    ports:
    - "80:80"
    networks:
    - vpcbr
    restart: always
    volumes:
    - "../data/www:/data/www:rw"
    - "../data/logs/nginx:/var/log/nginx"
    - "./nginx/conf.d:/etc/nginx/conf.d:ro"
    - "./nginx/certs/:/etc/nginx/certs"
    - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    command: "nginx -g 'daemon off;'"

version: "3"